server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://ep-green-brook-at8hrajg-pooler.c-9.us-east-1.aws.neon.tech/auth_db?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_gASOj1DN6Bha

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ThisIsMyVeryLongSecretKeyForMedInfoProject123456789
  expiration: 900000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: false