server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**,/api/users/**

            - id: medical-service
              uri: lb://MEDICAL-SERVICE
              predicates:
                - Path=/api/profile/**,/api/contacts/**,/api/emergency/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always