server:
  port: 8082

spring:
  datasource:
    url: ${MEDICAL_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      username: ${REDISUSER}
      password: ${REDISPASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always